ministryofjustice/hmpps-auth

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/security/JwtAuthenticationSuccessHandler.java
src/main/resources/application.yml
src/main/resources/db/auth/V1_2__oauth_client_details_increase_redirect.sql
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/LoginSpecification.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/pages/UserHomePage.groovy

Also minor improvements to app too

NN-1437: Increase size of redirect field to hold all notm urls

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/VerifyEmailController.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/verify/VerifyEmailService.java
src/main/resources/db/dev/data/auth/V9_1__oauth_sample_data.sql
src/main/resources/db/dev/data/nomis/V9_1__user_data.sql
src/main/resources/templates/verifyEmail.html
src/main/resources/templates/verifyEmailFailure.html
src/main/resources/templates/verifyEmailSent.html
src/main/resources/templates/verifyEmailSuccess.html
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/VerifyEmailSpecification.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/model/UserAccount.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/pages/VerifyEmailConfirmPage.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/pages/VerifyEmailPage.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/pages/VerifyEmailSentPage.groovy
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/VerifyEmailControllerTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/verify/VerifyEmailServiceIntTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/verify/VerifyEmailServiceTest.java

Needs some more styling and extra integration tests.
Will be disabled anyway until we want to start using it...

NN-1488: First stab at email front end

---

src/main/resources/templates/verifyEmail.html

Oops left old change password error messages in place

NN-1488 add email verification

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/security/JwtAuthenticationSuccessHandler.java
src/main/resources/templates/error/access-denied.html
src/main/resources/templates/index.html
src/main/resources/templates/verifyEmail.html
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/ChangePasswordSpecification.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/LoginSpecification.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/VerifyEmailSpecification.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/pages/HomePage.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/pages/VerifyEmailPage.groovy
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/security/JwtAuthenticationSuccessHandlerTest.java

Also NN-1548: Start to add in landing page after authentication

NN-1488: Add test of verification for existing email

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/ResetPasswordController.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/verify/ResetPasswordService.java
src/main/resources/templates/setPassword.html
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/ResetPasswordControllerTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/verify/ResetPasswordServiceTest.java

NN-1203: Add in setting of new password

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/ResetPasswordController.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/ResetPasswordControllerTest.java

Reverts ministryofjustice/nomis-oauth2-server#169
Reverting as now worked out why service wasn't throttling after 6 requests - we have two servers :man_facepalming:

Revert "NN-1726: Temporarily log ip address for success so can see why not be…"

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/HomeController.java
src/main/resources/templates/landing.html
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/HomeControllerTest.java

otherwise we ended up with some rows only containing one entry

NN-1741: Move role checking into controller so that we get rows of three

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/api/PingEndpoint.java
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/api/specs/PingSpecification.groovy
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/api/PingEndpointTest.java

Superagent failed to parse the raw value 'pong' as json

DT-8 Return plain/text from ping controller.

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/auth/model/UserEmailFilter.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/auth/repository/UserEmailRepository.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/maintain/AuthUserGroupService.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/maintain/AuthUserService.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/api/AuthUserController.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/api/AuthUserGroupsController.java
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/api/specs/AuthUserSpecification.groovy
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/auth/repository/GroupRepositoryTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/auth/repository/UserEmailRepositoryTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/maintain/AuthUserServiceTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/api/AuthUserControllerTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/api/AuthUserGroupsControllerTest.java

Also fix get groups to return list sorted by group name

DT-77: Initial stab at proper auth search

---

src/main/resources/db/dev/data/auth/V900_0__oauth_sample_data.sql

PAT-293: Enable client credentials for Pathfinder client in dev data

---

Procfile

https://devcenter.heroku.com/articles/procfile

HDC-heroku-fix Add Procfile to tell Heroku which Jar to run:

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/config/AuthenticationManagerConfiguration.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/MfaController.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/service/MfaService.kt
src/main/resources/db/dev/data/auth/V900_0__oauth_sample_data.sql
src/main/resources/templates/mfaChallenge.html
src/main/resources/templates/mfaResend.html
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/MfaSpecification.groovy
src/test/groovy/uk/gov/justice/digital/hmpps/oauth2server/integration/specs/pages/MfaResendPage.groovy
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/MfaControllerTest.kt

Based off the same page from gov.uk notify:

DT-423: Add in mfa resend page

---

build.gradle
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/auth/model/Person.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/maintain/AuthUserService.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/UserDetailsController.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/security/JwtAuthenticationSuccessHandler.java
src/main/resources/messages.properties
src/main/resources/templates/userDetails.html
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/maintain/AuthUserServiceTest.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/UserDetailsControllerTest.kt

DT-383: First stab at user details changes

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/maintain/AuthUserService.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/VerifyEmailController.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/verify/ResetPasswordServiceImpl.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/verify/VerifyEmailService.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/maintain/AuthUserServiceTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/VerifyEmailControllerTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/verify/ResetPasswordServiceTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/verify/VerifyEmailServiceIntTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/verify/VerifyEmailServiceTest.kt

update firstName parameter for change initial password email to take full name 
and added fullName to notify parameters for all email parameter sets which have firstName in already

DT 621 change initial password email changes

---

build.gradle.kts
src/main/resources/application.yml
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/HealthIntTest.kt

Fix CVEs raised by the scheduled OWASP job

DT-868 security fixes

---

src/main/resources/db/auth/V4_08__add_pathfinder_hq_role.sql

Create a national pathfinder role

PAT-675 Create national reporting permission

---

src/main/java/uk/gov/justice/digital/hmpps/oauth2server/config/JWTTokenEnhancer.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/config/TrackingTokenServices.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/security/ExternalIdAuthenticationHelper.java
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/config/JWTTokenEnhancerTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/config/TrackingTokenServicesTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/security/ExternalIdAuthenticationHelperTest.kt

Reverts ministryofjustice/hmpps-auth#530

Revert "DT-1108: 🔥 Remove username validation for client credentials"

---

.editorconfig
build.gradle.kts
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/config/JWTTokenEnhancer.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/config/OAuth2AuthorizationServerConfig.java
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/UserSelectorAuthorizationEndpoint.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/resource/UserSelectorController.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/security/UserContextApprovalHandler.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/security/UserService.kt
src/main/java/uk/gov/justice/digital/hmpps/oauth2server/service/UserContextService.kt
src/main/resources/templates/userSelector.html
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/config/JWTTokenEnhancerTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/config/TrackingTokenServicesTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/integration/ClientLoginSpecification.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/resource/UserSelectorAuthorizationEndpointTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/security/UserContextApprovalHandlerTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/security/UserServiceTest.kt
src/test/java/uk/gov/justice/digital/hmpps/oauth2server/service/UserContextServiceTest.kt

At present will just work for the single user matched scenario.
Need to add some tests for the changes.

DT-1072: ✨ Map multi user and single user azuread

---

src/main/resources/db/dev/data/auth/V900_0__oauth_sample_data.sql

Adding some test/local development credentials for the PECS calculate journey variable payments project.
Project linked here - [Calculate Journey Variable Payments](https://github.com/ministryofjustice/calculate-journey-variable-payments)

P4-2392 add test credentials for the PECS calculate journey variable payments project.

---

build.gradle.kts

deleted lib folder ( including ojdbc jar) and added it as a gradle dependency

Dt 1247 use ojdbcjar gradle dependency

---

src/main/resources/db/auth/V5_07__pecs_group_removals.sql
src/main/resources/db/auth/V5_08__pecs_role_removals.sql

DT-1292 removed unused groups and roles

---

src/main/resources/db/dev/data/auth/V900_0__oauth_sample_data.sql

sorry for such a small inconsequential PR. i missed this when adding the new test client config. thanks.

add ROLE_INTERVENTIONS to interventions test client

---

Dockerfile
applicationinsights.json
src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/config/VersionOutputter.kt

Reverts ministryofjustice/hmpps-auth#676

Revert "DT-1297 - Add app version and role name to app insights tracing"

---

helm_deploy/hmpps-auth/templates/_envs.tpl
helm_deploy/secrets-example.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/config/ApplicationInsightsConfiguration.kt

Reverts ministryofjustice/hmpps-auth#670

Revert "DT-1297 - Upgrade to App Insights agent V3"

---

src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/resource/ResetPasswordController.kt
user-load.sh

Renaming misleading variable
Correcting upload script instructions
Removing adding of vary role as this will never be used again

Tidying up the upload script

---

src/main/resources/static/css/app.css
src/main/resources/static/js/card.js
src/main/resources/templates/fragments/layout.html
src/main/resources/templates/landing.html

DT-1466: 💄 Copy card layout from psh

---

src/main/resources/db/auth/V5_18__soc_roles_removals.sql
src/main/resources/db/dev/data/auth/V900_0__oauth_sample_data.sql

PAT-1219: Remove SOC Restricted role

---

helm_deploy/hmpps-auth/templates/deployment.yaml

Reverts ministryofjustice/hmpps-auth#753

Revert "Faster JVM startup."

---

src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/resource/api/PrisonUserController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/security/UserService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/oauth2server/resource/api/PrisonUserControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/oauth2server/security/UserServiceTest.kt

:bug: `activeCaseloadId` should be `activeCaseLoadId` (capital 'L')

DCS-864 Change activeCaseloadId to activeCaseLoadId

---

helm_deploy/hmpps-auth/templates/_envs.tpl

Repurpose the currently unused Delius role CTRBT003

PAT-1699 Add NSD users to the PF service

---

src/main/resources/db/dev/data/auth/V900_0__oauth_sample_data.sql

Add ARN client credentials to sample data

DT-2104: Add ARN client credentials to sample data
